[description]
name = pci
path = /sys/drivers/libpci.so
boot_start = true

[imports]
acpi

[exports]
fn walk_pci_cap_list(pci_dev: *const kernel_intf::driver::DeviceObject, match_cap_id: u8, callback: extern "C" fn(bus: u8, device: u8, function: u8, offset: u8, ctx: *mut core::ffi::c_void), ctx: *mut core::ffi::c_void)


[DeviceStack]
PNP0A03
pci

[DeviceStack]
PNP0A08
pci
