[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.x86_64]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Tkernel/config/x86_64/linker.ld"]