[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
uefi = { version = "*", features = [ "panic_handler", "alloc", "global_allocator" ] }
uefi-services = "*"
log = "*"

