[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
log.workspace = true
uefi = { version = "*", features = [ "alloc", "global_allocator" ] }
blr = {path = "../blr"}
