[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "*", features = [ "panic_handler", "logger", "alloc", "global_allocator" ] }
uefi-services = "*"
log = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

