[workspace]
resolver = "2"
members = [
    "boot/uefi",
    "kernel",
    "kernel/src/drivers/*"
]

[profile.dev]
panic = "abort"


[profile.release]
panic = "abort"


[workspace.dependencies]
common = {path = "lib/common"}
log = "*"