[description]
name = acpi
path = /sys/drivers/libacpi.so
boot_start = true

[exports]
fn acpi_get_irq(pdo: *const u8, bus: u8, addr: u32, pin: u8, out: *mut u8) -> bool
fn acpi_get_rb_info(pdo: *const u8, out_bus: *mut u8, out_seg: *mut u16) -> bool
fn acpi_pdo_get_handle(pdo_ctx: *const core::ffi::c_void) -> *mut core::ffi::c_void

[DeviceStack]
Root
acpi
