/sys/drivers/libi8042.so
/sys/drivers/libtty.so
/sys/drivers/libinput.so
/sys/drivers/libacpi.so
/sys/drivers/libpci.so
/sys/drivers/libec.so
/sys/drivers/libdisk.so
/sys/libtest1.so
/sys/libfat32.so
/sys/drivers/boot.conf
/bin/libc.so
/bin/signal_test
/bin/init
/bin/sh
/bin/producer
/bin/producer2
/bin/producer3
/bin/consumer
/bin/stdio_test
/bin/envtest