/sys/drivers/libi8042.so
/sys/drivers/libtty.so
/sys/drivers/libinput.so
/sys/drivers/libacpi.so
/sys/drivers/libpci.so
/sys/drivers/libec.so
/sys/drivers/libdisk.so
/sys/drivers/libvirt_blk.so
/sys/libtest1.so
/sys/libfat32.so
/sys/libbootanim.so
/sys/drivers/boot.conf
/bin/libc.so
/bin/signal_test
/bin/init
/bin/sh
/bin/producer
/bin/producer2
/bin/producer3
/bin/consumer
/bin/stdio_test
/bin/envtest
/bin/cat
/bin/echo
/bin/ls
/bin/ln
/bin/readlink
/bin/mkdir
/bin/rmdir
/bin/rm
/bin/fs_stress
/bin/sleep
/bin/shutdown
/bin/kill
/bin/ps
/bin/dmesg
/bin/suspend_test
/bin/head
/bin/tail
/bin/wc
/bin/cp
/bin/mv
/conf/init_sh